apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      # - ./infra/k8s/*
      - ./infra/k8s/auth-mongo-depl.yaml
      - ./infra/k8s/auth-depl.yaml
      - ./infra/k8s/gig-mongo-depl.yaml
      - ./infra/k8s/gig-depl.yaml
      - ./infra/k8s/admin-mongo-depl.yaml
      - ./infra/k8s/admin-depl.yaml

      - ./infra/k8s/client-depl.yaml
build:
  local:
    push: false
  artifacts:
    - image: zaouiamine/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: zaouiamine/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # - image: zaouiamine/profile
    #   context: profile
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    - image: zaouiamine/gig
      context: gig
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: zaouiamine/admin
      context: admin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: zaouiamine/review
    #   context: review
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
