apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: zaouiamine/auth
      # the folder that contains the src code for the image
      context: auth
      # docker file to use
      docker:
        dockerfile: Dockerfile
      # how to handle any files that change inside here
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: zaouiamine/client
      # the folder that contains the src code for the image
      context: client
      # docker file to use
      docker:
        dockerfile: Dockerfile
      # how to handle any files that change inside here
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    # - image: zaouiamine/profile
    #   # the folder that contains the src code for the image
    #   context: profile
    #   # docker file to use
    #   docker:
    #     dockerfile: Dockerfile
    #   # how to handle any files that change inside here
    #   sync:
    #     manual:
    #       - src: "**/*.js"
    #         dest: .
