import "./globals.css";

export const metadata = {
  title: "Hirafee",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <div className="flex-center">{children}</div>
      </body>
    </html>
  );
}
