apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigs
  template:
    metadata:
      labels:
        app: gigs
    spec:
      containers:
        - name: gigs
          image: malakboudaa/gigs
          env:
            - name: MONGO_URI
              value: 'mongodb://gigs-mongo-srv:27017/gigs'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: gigs-srv
spec:
  selector:
    app: gigs
  ports:
    - name: gigs
      protocol: TCP
      port: 3000
      targetPort: 3000
